### ISSUE TITLE
how do I run this thing?

### ISSUE THREAD

**Issue by originalnickname** [gladiatortoise/node-apiless-youtube-upload#15]
I installed node-apiless-youtube-upload by running "npm -i node-apiless-youtube-upload" and I am trying to run this script:

`import YoutubeUploader from 'node-apiless-youtube-upload'

(async () => {
    const youtubeUploader = new YoutubeUploader()
    const cookiesPath = process.cwd() + '/cookies_saved.json'

    // Try loading cookies from disk
    try {
        await youtubeUploader.loadCookiesFromDisk(cookiesPath)

        if (!(await youtubeUploader.checkCookiesValidity())) {
            throw new Error('Cookies loaded from disk are not valid')
        }
    } catch(e) {
        console.log('Prompting Google login..')

        // Open a login window for Google account. Cookies will be stored in the youtubeUploader instance
        await youtubeUploader.promptLoginAndGetCookies()

        // Save cookies
        await youtubeUploader.saveCookiesToDisk(cookiesPath)
    }
    
    // Upload a video to youtube
    await youtubeUploader.uploadVideo({
        videoPath: 'final.mp4',
        title: 'Uploaded Video',
        description: 'This is a placeholder description.',
        thumbnailPath: 'TestThumbnail.jpg',
        visibility: 'public',
        monetization: false
    })
})()`

by running
`node --harmony es6c.mjs`
in terminal.

this is my output:
`file:///home/user/Desktop/test/es6c.mjs:4
    const youtubeUploader = new YoutubeUploader()
                            ^

TypeError: YoutubeUploader is not a constructor
    at file:///home/user/Desktop/test/es6c.mjs:4:29
    at file:///home/user/Desktop/test/es6c.mjs:33:3
    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)`

what am I doing wrong?

**Comment by gladiatortoise** [comment]
Hi man try this:
```
const youtubeUploader = new YoutubeUploader.default()
```

**Comment by originalnickname** [comment]
I changed it and ran the script. now it says:

`Prompting Google login..
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at normalizeSpawnArguments (node:child_process:433:3)
    at spawn (node:child_process:592:13)
    at Object.spawnWithSignal [as spawn] (node:child_process:761:17)
    at runUncontrolledChrome (/home/o3/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:66:43)
    at makeLoggedInChromeProfile (/home/o3/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:99:12)
    at async Object.exports.default (/home/o3/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:128:23)
    at async YoutubeUploader.promptLoginAndGetCookies (/home/o3/node_modules/node-apiless-youtube-upload/dist/YoutubeUploader.js:16:24)
    at async file:///home/o3/Desktop/test/es6c2.mjs:19:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}
`

**Comment by gladiatortoise** [comment]
I believe you don't have chrome installed

**Comment by originalnickname** [comment]
you are right, I had Chromium installed. I installed chrome just yet and reinstalled node-apiless-youtube-upload again.
Still got this error now:

```
Prompting Google login..
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at normalizeSpawnArguments (node:child_process:433:3)
    at spawn (node:child_process:592:13)
    at Object.spawnWithSignal [as spawn] (node:child_process:761:17)
    at runUncontrolledChrome (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:66:43)
    at makeLoggedInChromeProfile (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:99:12)
    at async Object.exports.default (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:128:23)
    at async YoutubeUploader.promptLoginAndGetCookies (/home/user/node_modules/node-apiless-youtube-upload/dist/YoutubeUploader.js:16:24)
    at async file:///home/o3/Desktop/test/es6c2.mjs:19:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by gladiatortoise** [comment]
Did you restart the command line after installing chrome?

**Comment by originalnickname** [comment]
> Did you restart the command line after installing chrome?

Yes, and I rebooted the machine too.

here is the output again:
```
node --harmony es6c2.mjs
Prompting Google login..
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at normalizeSpawnArguments (node:child_process:433:3)
    at spawn (node:child_process:592:13)
    at Object.spawnWithSignal [as spawn] (node:child_process:761:17)
    at runUncontrolledChrome (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:66:43)
    at makeLoggedInChromeProfile (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:99:12)
    at async Object.exports.default (/home/user/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:128:23)
    at async YoutubeUploader.promptLoginAndGetCookies (/home/user/node_modules/node-apiless-youtube-upload/dist/YoutubeUploader.js:16:24)
    at async file:///home/user/Desktop/test/es6c2.mjs:19:9 {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by gladiatortoise** [comment]
Can you try running these:
```
npm i chrome-location -g
```
```
chrome-location
```
Does it return chrome path or null?

**Comment by originalnickname** [comment]
it returns 'null'

**Comment by gladiatortoise** [comment]
This is a problem with https://github.com/hughsk/chrome-location then. I will try to find a workaround later

**Comment by originalnickname** [comment]
maybe it's because of my setup. I hardened my system, so /, /var and /home are on different partitions with different rules. also I use apparmor and firejail.

**Comment by sigalor** [comment]
I chose to use the NPM module `chrome-paths` instead of `chrome-location` and then used the following to determine the Chrome/Chromium path in `runUncontrolledChrome` in `promptLoginAndGetCookies`:

```
import chromePaths from 'chrome-paths'
// ...
const runUncontrolledChrome = async (userDataDir: string): Promise<void> => {
    const chromeLocation = chromePaths.chrome ?? chromePaths.chromeCanary ?? chromePaths.chromium
    const chromeProcess = spawn(chromeLocation, [
    // ...
```

**Comment by barenca** [comment]
Amazon Linux 2:

sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
