### ISSUE TITLE
[Centos 8] DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by nuagoz** [gladiatortoise/node-apiless-youtube-upload#17]
```
Prompting Google login..
[Error: ENOENT: no such file or directory, open '/tmp/node-apiless-youtube-upload-NTn1eR/Default/Preferences'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/node-apiless-youtube-upload-NTn1eR/Default/Preferences'
}
(node:15847) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/home/centos/projects/yt-clips/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/home/centos/projects/yt-clips/node_modules/selenium-webdriver/lib/http.js:671:13)
    at Executor.execute (/home/centos/projects/yt-clips/node_modules/selenium-webdriver/lib/http.js:597:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gladiatortoise** [comment]
Hi! I personally was not aware of this issue, as I've ran tests on Ubuntu. The error "DevToolsActivePort file doesn't exist" seems to be pretty popular on stackoverflow : https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t
One guy suggests flags
```python
       "--no-sandbox",
       "--disable-dev-shm-usage"
```

I don't know if you're interested in debugging this, but my first priority is right now to get this running on macos and then different linux distros

**Comment by sigalor** [comment]
I had the same issue on Ubuntu 20.04 and adding the following line when constructing the Chrome options in `makeWebDriver.ts` fixed it for me:

```
chromeOptions.addArguments('--remote-debugging-port=9222')
```
