### ISSUE TITLE
Rare random hangs

### ISSUE THREAD

**Issue by shitpoet** [gladiatortoise/node-apiless-youtube-upload#18]
Sometimes the script hangs on 'Initializing video'.

```
Settings cookies..
Opening Youtube Studio..
Initializing video..
WebDriverError: disconnected: Unable to receive message from renderer
  (Session info: headless chrome=87.0.4280.141)
    at Object.throwDecodedError (/home/ors/.npm-packages/lib/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/home/ors/.npm-packages/lib/node_modules/selenium-webdriver/lib/http.js:671:13)
    at Executor.execute (/home/ors/.npm-packages/lib/node_modules/selenium-webdriver/lib/http.js:597:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Driver.execute (/home/ors/.npm-packages/lib/node_modules/selenium-webdriver/lib/webdriver.js:729:17)
    at async Driver.findElements (/home/ors/.npm-packages/lib/node_modules/selenium-webdriver/lib/webdriver.js:1022:17) {
  remoteStacktrace: '#0 0x555555b79e79 <unknown>\n'
}
```

I'm thinking about debugging the error, but I can not reproduce it consistently. 

This happens for me once a day approximately.

**Comment by evilive3000** [comment]
Looks like chrome did not finish loading the page or get it corrupted. 
I can suggest you wrap this part of the code into try...catch and handle this error on your own as a quick fix.
