### ISSUE TITLE
(node:12381) UnhandledPromiseRejectionWarning: TypeError: YoutubeUploader is not a constructor

### ISSUE THREAD

**Issue by MohamedIrfanAM** [gladiatortoise/node-apiless-youtube-upload#26]
I ran  this code by `node --harmony es6.mjs`

```
import YoutubeUploader from 'node-apiless-youtube-upload'

(async () => {
    const youtubeUploader = new YoutubeUploader()
    const cookiesPath = process.cwd() + '/cookies_saved.json'

    // Try loading cookies from disk
    try {
        await youtubeUploader.loadCookiesFromDisk(cookiesPath)

        if (!(await youtubeUploader.checkCookiesValidity())) {
            throw new Error('Cookies loaded from disk are not valid')
        }
    } catch(e) {
        console.log('Prompting Google login..')

        // Open a login window for Google account. Cookies will be stored in the youtubeUploader instance
        await youtubeUploader.promptLoginAndGetCookies()

        // Save cookies
        await youtubeUploader.saveCookiesToDisk(cookiesPath)
    }
    
    // Upload a video to youtube
    await youtubeUploader.uploadVideo({
        videoPath: '/home/semeeha/Documents/Upload/test.mp4',
        title: '📡 Automatically Uploaded Video 📡',
        description: 'This is a placeholder description.',
        thumbnailPath: '',
        visibility: 'unlisted',
        monetization: false
    })
})()
```
I got the following error

```
(node:12381) ExperimentalWarning: The ESM module loader is experimental.
(node:12381) UnhandledPromiseRejectionWarning: TypeError: YoutubeUploader is not a constructor
    at file:///home/semeeha/Documents/Upload/.src/node-apiless-youtube-upload/es6.mjs:4:29
    at file:///home/semeeha/Documents/Upload/.src/node-apiless-youtube-upload/es6.mjs:33:3
    at ModuleJob.run (internal/modules/esm/module_job.js:137:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
(node:12381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
I don't have any experience with node and js please help

**Comment by tackelua** [comment]
I got the same error, just use the sample code and got the error :(
