### ISSUE TITLE
invalid cookie domain: Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by ranahaani** [gladiatortoise/node-apiless-youtube-upload#31]
``` js
Prompting Google login..
Settings cookies..
(node:3805) UnhandledPromiseRejectionWarning: InvalidCookieDomainError: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: headless chrome=95.0.4638.69)
    at Object.throwDecodedError (/home/username/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/home/username/node_modules/selenium-webdriver/lib/http.js:643:13)
    at Executor.execute (/home/username/node_modules/selenium-webdriver/lib/http.js:569:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Driver.execute (/home/username/node_modules/selenium-webdriver/lib/webdriver.js:732:17)
    at async Object.exports.default (/home/username/node_modules/node-apiless-youtube-upload/dist/methods/uploadVideo.js:112:13)
    at async /home/username/.config/JetBrains/script.ts:25:5
(node:3805) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:3805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by kotsh23** [comment]
any luck?
