### ISSUE TITLE
chrome_1.default.setDefaultService is not a function

### ISSUE THREAD

**Issue by Milk-Cool** [gladiatortoise/node-apiless-youtube-upload#33]
**System:** Pop!_OS 20.04, Linux 5.17.5
**NodeJS version**: 18.6.0
**Library version**: 1.1.9

When trying to upload a test video via the library, after getting the cookies it throws this error:
```
/home/censoredusername/Документы/GitHub/wikivideo/node_modules/node-apiless-youtube-upload/dist/helpers/makeWebDriver.js:52
    chrome_1.default.setDefaultService(new chrome_1.default.ServiceBuilder(webdriverPath).build());
                     ^

TypeError: chrome_1.default.setDefaultService is not a function
    at exports.makeWebDriver (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/node-apiless-youtube-upload/dist/helpers/makeWebDriver.js:52:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:129:21)
    at async upload (/home/censoredusername/Документы/GitHub/wikivideo/index.js:58:18)

```

My code:
```javascript

// Parameters
const description = `
	Test description
`;
// ...
// YT upload
async function upload(filename, title){
	const cookies = await promptLoginAndGetCookies();
	await uploadVideo({
		"videoPath": filename,
		"title": title,
		"thumbnailPath": "PNG.png",
		"visibility": "public",
		"description": description,
		"monetization": true
	}, cookies);
}
upload("test.mp4", "Test video").then(console.log);
```

**Comment by Milk-Cool** [comment]
```javascript
const { promptLoginAndGetCookies, uploadVideo } = require("node-apiless-youtube-upload");
```

**Comment by Milk-Cool** [comment]
I've found an issue that told me about the broken 4.3.1 version of `selenium-webdriver`: dequelabs/axe-core-npm#538.
My solution was to manually downgrade it to 4.3.0. But now I get another error:
```
/home/censoredusername/Документы/GitHub/wikivideo/node_modules/selenium-webdriver/lib/error.js:522
    let err = new ctor(data.message)
              ^

WebDriverError: unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
    at Object.throwDecodedError (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/selenium-webdriver/lib/webdriver.js:740:17)
    at async fetchCookies (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:105:5)
    at async exports.default (/home/censoredusername/Документы/GitHub/wikivideo/node_modules/node-apiless-youtube-upload/dist/methods/promptLoginAndGetCookies.js:130:16)
    at async upload (/home/censoredusername/Документы/GitHub/wikivideo/index.js:59:18) {
  remoteStacktrace: '#0 0x55b985b2cb13 <unknown>\n' +
    '#1 0x55b985933688 <unknown>\n' +
    '#2 0x55b985920d58 <unknown>\n' +
    '#3 0x55b985920372 <unknown>\n' +
    '#4 0x55b98591f815 <unknown>\n' +
    '#5 0x55b98591ef54 <unknown>\n' +
    '#6 0x55b98593a7d1 <unknown>\n' +
    '#7 0x55b98599bf98 <unknown>\n' +
    '#8 0x55b9859887a3 <unknown>\n' +
    '#9 0x55b98595e0ea <unknown>\n' +
    '#10 0x55b98595f225 <unknown>\n' +
    '#11 0x55b985b742dd <unknown>\n' +
    '#12 0x55b985b782c7 <unknown>\n' +
    '#13 0x55b985b5e22e <unknown>\n' +
    '#14 0x55b985b790a8 <unknown>\n' +
    '#15 0x55b985b52bc0 <unknown>\n' +
    '#16 0x55b985b956c8 <unknown>\n' +
    '#17 0x55b985b95848 <unknown>\n' +
    '#18 0x55b985bafc0d <unknown>\n' +
    '#19 0x7fbf2ae68609 <unknown>\n'
}
```

**Comment by Milk-Cool** [comment]
I've found out that the latest version of `selenium-webdriver` at the moment when latest pull request was commited was 4.0.0-beta-1 and the latest stable version was 3.150.0. Gonna try downloading both of these versions.

**Comment by Milk-Cool** [comment]
4.0.0-beta.1 didn't work

**Comment by Milk-Cool** [comment]
3.150.0 doesn't exist for npm, trying version 3.6.0

**Comment by Milk-Cool** [comment]
Version 3.6.0: same error. Maybe I'll just go with 4.3.0 and try to fix THAT error.

**Comment by Milk-Cool** [comment]
are you fucking serious
`TypeError: chrome_1.default.setDefaultService is not a function`

**Comment by ekus447** [comment]
it happens to me too

**Comment by MoJongleur** [comment]
@Milk-Cool 
In new versions selenium-webdriver was deleted method "setDefaultService"
I set version "selenium-webdriver": "~4.1.0" and it works fine
